Articles
udsleeds/openinfra pull request #33
Opened 2022-02-04 11:27 UTC by GretaTimaite

2022-02-04 12:37 UTC, Robinlovelace requested changes
Need to get the tests passing.

2022-02-04 18:39 UTC, GretaTimaite commented
A quick question: I've downgraded `roxygen2` from version = 7.1.2 to version = 7.1.1 as it was giving me a warning when running checks. Should I have kept the newest version?

Now there's only one warning regarding R version; not sure if I should be concerned about it and/or maybe somehow specify it in the DESCRIPTION file?
` NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.`

2022-02-06 17:53 UTC, Robinlovelace approved these changes
Happy for this to be merged great work on getting actions working (except on pesky Mac OS) :rocket:

2022-02-06 18:16 UTC, GretaTimaite commented on vignettes/osmintro.Rmd
>  saveRDS(leeds, # name of an object in R
Hm, maybe. I will have a look at it tomorrow. But if I use `download.file()`, doesn't it kind of defeat the purpose of loading the RDS file from one's directory?

2022-02-06 18:53 UTC, Robinlovelace commented on vignettes/osmintro.Rmd
>  saveRDS(leeds, # name of an object in R
Depends what the purpose is.

2022-02-08 12:37 UTC, Robinlovelace commented
Now it's the Windows ones that are failing :facepalm: 

I suggest you merge this now @GretaTimaite

2022-02-08 13:28 UTC, merged